#!/usr/bin/env bash
# this script displays hi on the nith iteration using while loop
count=1
while [ $count -le 10 ]; do
	if [ $count = 9 ]; then
		echo Best School
	       echo Hi	
       else
	       echo Best School
	fi
	let count=count+1
done 
