#!/usr/bin/env bash
# This script dispays best school except for the 4th and 8th iterations.
count=1
while [ $count -le 10 ]; do
if [ $count -eq 4 ]; then
echo bad luck 
elif [ $count -eq 8 ]; then 
echo good luck
else 
echo Best School
fi
let count=count+1
done 
