#!/usr/bin/env bash
# This script displays bad luck after 4, good luck after 8 and bad luck after 17
count=1 
while [ $count -le 20 ]; do
	case $count in 
		4)
			echo 4
			echo bad luck from China
			;;
		9)
			echo 9
			echo bad luck from Japan
			;;
		17)
			echo 17
			echo bad luck from Italy
			;;
		*)
			echo $count
			;;
	esac
	let count=count+1
done 
